api/urls.py
from django.urls import path

from api import views

app_name = "api"


urlpatterns = [
    path('v1/list/grantgoal/', views.ListGrantGoalAPIView.as_view(), name="gg_list"),
    path('v1/create/grantgoal/', views.CreateGrantGoalAPIView.as_view(), name="gg_create"),
    path('v1/detail/grantgoal/<int:pk>/', views.DetailGrantGoalAPIView.as_view(), name="gg_detail"),
    path('v1/update/grantgoal/<int:pk>/', views.UpdateGrantGoalAPIView.as_view(), name="gg_update"),
    path('v1/delete/grantgoal/<int:pk>/', views.DeleteGrantGoalAPIView.as_view(), name="gg_delete"),
]

home/urls.py
from django.urls import path

from home import views

app_name = "home"


urlpatterns = [
    path('', views.Index.as_view(), name="index"),
    path('logout/', views.Logout.as_view(), name="logout"),
    path('signup/', views.SignUp.as_view(), name="signup"),
    path('about/', views.About.as_view(), name="about"),
]

plaestem/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('api/', include("api.urls")),
    path('core/', include("core.urls")),
    path('clientapi/', include("clientapi.urls")),
]

home/models.py
from django.db import models

# Create your models here.


class Algo(models.Model):
    name = models.CharField(max_length=16)
    email = models.CharField(max_length=16)
    age = models.IntegerField()
    status = models.BooleanField(default=True)
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name

home/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm



class LoginForm(forms.Form):
    username = forms.CharField(max_length=32, widget=forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe tu Username"}))
    password = forms.CharField(max_length=32, widget=forms.PasswordInput(attrs={"type":"password", "class":"form-control", "placeholder":"Escribe tu Password"}))


class SignUpForm(UserCreationForm):
    username = forms.CharField(max_length=16, widget=forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe tu Username"})) 
    password1 = forms.CharField(max_length=32, widget=forms.PasswordInput(attrs={"type":"password", "class":"form-control", "placeholder":"Escribe tu Password"}))
    password2 = forms.CharField(max_length=32, widget=forms.PasswordInput(attrs={"type":"password", "class":"form-control", "placeholder":"Confirma tu Password"}))  
    first_name = forms.CharField(max_length=16, widget=forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe tu First Name"})) 
    last_name = forms.CharField(max_length=16, widget=forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe tu Last Name"})) 
    email = forms.EmailField(max_length=32, widget=forms.EmailInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe tu Email"})) 

home/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate


from .forms import LoginForm, SignUpForm
# Create your views here.


class Index(generic.View):
    template_name = "home/index.html"
    context = {}
    form_class = LoginForm

    def get(self, request):
        self.context = {
            "username": "Foo Bar",
            "email": "foo@bar.com",
            "users": User.objects.all(),
            "form": self.form_class
        }
        return render(request, self.template_name, self.context)
    
    def post(self, request, **kwargs):
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect("home:index")

        return redirect("home:index")


class Logout(generic.View):
    def get(self, request):
        logout(request)
        return redirect("home:index")


class SignUp(generic.CreateView):
    template_name = "home/signup.html"
    model = User
    form_class = SignUpForm
    success_url = reverse_lazy("home:index")



class About(generic.View):
    template_name = "home/about.html"
    context = {}

    def get(self, request):
        return render(request, self.template_name, self.context)

templates/home/about.html
{% extends 'base/base.html' %}

{% block title %}ABOUT VIEW{% endblock title %}

{% block content %}

    <h1>Hola Soy el About </h1>


{% endblock content %}

{% block left %}
    <form action="">
        <input type="number" name="" id="">
        <button class="btn btn-outline-danger">left</button>
    </form>
{% endblock left %}

templates/home/index.html
{% extends 'base/base.html' %}

{% block title %}INDEX VIEW{% endblock title %}

{% block left %}
    <form action="">
        <input type="number" name="" id="">
        <button class="btn btn-outline-danger">left</button>
    </form>
{% endblock left %}

{% block content %}

    {% if request.user.is_authenticated %}
    <h1>Bienvenido a PLAEST user: {{ request.user }} </h1>

    <table class="table">
        <thead>
            <th>Username</th>
            <th>Email</th>
            <th>First Name</th>
            <th></th>
            <th>Actions</th>
            <th></th>
        </thead>
        <tbody>
            {% for user in users %}
                <tr>
                    <td>{{ user.username }}</td>
                    <td>{{ user.email }}</td>
                    <td>{{ user.first_name }}</td>
                    <td><a href="" class="btn btn-outline-info">Detail</a></td>
                    <td><a href="" class="btn btn-outline-warning">Update</a></td>
                    <td><a href="" class="btn btn-outline-danger">Delete</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    {% else %}
    <hr>
    <br>
        <form action="" method="post">
            {% csrf_token %}
                {{ form }}
                <hr>
            <button type="submit" class="btn btn-outline-success form-control">LogIn</button>
            <a href="" class="btn btn-outline-warning form-control">Cancel</a>
        </form>
        <a href="{% url 'home:signup' %}">Registrate Aqui</a>
    {% endif %}

               
{% endblock content %}    

    

templates/home/signup.html
{% extends "base/base.html" %}

{% block title %}SIGNUP VIEW{% endblock title %}

{% block content %}
    <form action="" method="post">
    {% csrf_token %}
        {{ form }}
        <hr>
        <button type="submit" class="btn btn-outline-success form-control">SignUp</button>
        <a href="{% url 'home:index' %}" class="btn btn-outline-warning form-control">Cancel</a>
    </form> 
{% endblock content %}