api/urls.py
from django.urls import path

from api import views

app_name = "api"


urlpatterns = [
    path('v1/list/grantgoal/', views.ListGrantGoalAPIView.as_view(), name="gg_list"),
    path('v1/create/grantgoal/', views.CreateGrantGoalAPIView.as_view(), name="gg_create"),
    path('v1/detail/grantgoal/<int:pk>/', views.DetailGrantGoalAPIView.as_view(), name="gg_detail"),
    path('v1/update/grantgoal/<int:pk>/', views.UpdateGrantGoalAPIView.as_view(), name="gg_update"),
    path('v1/delete/grantgoal/<int:pk>/', views.DeleteGrantGoalAPIView.as_view(), name="gg_delete"),
]

core/urls.py
from django.urls import path

from core import views

app_name = "core"


urlpatterns = [
    path('list/grantgoal/', views.ListGrantGoal.as_view(), name="list_gg"),
    path('detail/grantgoal/<int:pk>/', views.DetailGrantGoal.as_view(), name="detail_gg"),
    path('update/grantgoal/<int:pk>/', views.UpdateGrantGoal.as_view(), name="update_gg"),
    path('delete/grantgoal/<int:pk>/', views.DeleteGrantGoal.as_view(), name="delete_gg"),
    path('create/grantgoal/', views.CreateGrantGoal.as_view(), name="create_gg"),
]

home/urls.py
from django.urls import path

from home import views

app_name = "home"


urlpatterns = [
    path('', views.Index.as_view(), name="index"),
    path('logout/', views.Logout.as_view(), name="logout"),
    path('signup/', views.SignUp.as_view(), name="signup"),
    path('about/', views.About.as_view(), name="about"),
]

plaestem/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('api/', include("api.urls")),
    path('core/', include("core.urls")),
    path('clientapi/', include("clientapi.urls")),
]

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
    <div class="row">
        <div class="col">
            <nav class="navbar navbar-expand-lg bg-body-tertiary">
                <div class="container-fluid">
                  <a class="navbar-brand" href="#">Navbar</a>
                  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                  </button>
                  <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                      <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'home:index' %}">Home</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'home:about' %}">About</a>
                      </li>
                      <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                          Actions
                        </a>
                        <ul class="dropdown-menu">
                          <li><a class="dropdown-item" href="{% url 'core:list_gg' %}">List GrantGoal</a></li>
                          <li><a class="dropdown-item" href="{% url 'core:create_gg' %}">Create Grant Goal</a></li>
                          <li><hr class="dropdown-divider"></li>
                          <li><a class="dropdown-item" href="#">Something else here</a></li>
                        </ul>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link disabled" aria-disabled="true">Disabled</a>
                      </li>
                    </ul>
                  <a href="{% url  'home:logout' %}">LogOut</a>
                    <form class="d-flex" role="search">
                      <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                      <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
                  </div>
                </div>
              </nav>
        </div>
    </div>
    <div class="row">
        <div class="col-2">
          {% block left %}
          {% endblock left %}
        </div>
        <div class="col-8">
            {% block content %}
            {% endblock content %}
        </div>
        <div class="col-2"></div>
    </div>
    <div class="row">
        <div class="col"></div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap.min.js' %}" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap.js' %}" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>