api/urls.py
from django.urls import path

from api import views

app_name = "api"


urlpatterns = [
    path('v1/list/grantgoal/', views.ListGrantGoalAPIView.as_view(), name="gg_list"),
    path('v1/create/grantgoal/', views.CreateGrantGoalAPIView.as_view(), name="gg_create"),
    path('v1/detail/grantgoal/<int:pk>/', views.DetailGrantGoalAPIView.as_view(), name="gg_detail"),
    path('v1/update/grantgoal/<int:pk>/', views.UpdateGrantGoalAPIView.as_view(), name="gg_update"),
    path('v1/delete/grantgoal/<int:pk>/', views.DeleteGrantGoalAPIView.as_view(), name="gg_delete"),
]

core/urls.py
from django.urls import path

from core import views

app_name = "core"


urlpatterns = [
    path('list/grantgoal/', views.ListGrantGoal.as_view(), name="list_gg"),
    path('detail/grantgoal/<int:pk>/', views.DetailGrantGoal.as_view(), name="detail_gg"),
    path('update/grantgoal/<int:pk>/', views.UpdateGrantGoal.as_view(), name="update_gg"),
    path('delete/grantgoal/<int:pk>/', views.DeleteGrantGoal.as_view(), name="delete_gg"),
    path('create/grantgoal/', views.CreateGrantGoal.as_view(), name="create_gg"),
]

plaestem/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('api/', include("api.urls")),
    path('core/', include("core.urls")),
    path('clientapi/', include("clientapi.urls")),
]

core/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import timedelta
from django.db.models.signals import post_save
from django.dispatch import receiver


# Create your models here.


class Area(models.Model):
    area_name = models.CharField(max_length=64, default="Generic Area")
    timestamp = models.DateField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.area_name



CHOICES_STATE = (
    ("Done", "DN"),
    ("Doing", "DG"),
    ("Not Stared", "NS"),
)

class GrantGoal(models.Model):
    gg_name = models.CharField(max_length=128, default="Generic Grant Goal")
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.CharField(max_length=256, default="Generic Grant Goal Description")
    days_durations = models.IntegerField(default=7)
    timestamp = models.DateField(auto_now_add=True, auto_now=False)
    final_date = models.DateField(auto_now_add=False, auto_now=False, null=True, blank=True)
    area = models.ForeignKey(Area, on_delete=models.CASCADE)
    state = models.CharField(max_length=16, choices=CHOICES_STATE)
    status = models.BooleanField(default=True)
    slug = models.SlugField(max_length=16)

    def __str__(self):
        return self.gg_name


## SIGNALS 
### post_save
@receiver(post_save, sender=GrantGoal)
def final_date_grantgoal(sender, instance, **kwargs):
    if instance.final_date is None or instance.final_date=='':
        instance.final_date = instance.timestamp + timedelta(days=instance.days_durations)
        instance.save()



class SubGrantGoal(models.Model):
    sgg_name = models.CharField(max_length=128, default="Generic Grant Goal")
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    grantgoal = models.ForeignKey(GrantGoal, on_delete=models.CASCADE)
    description = models.CharField(max_length=256, default="Generic Grant Goal Description")
    days_durations = models.IntegerField(default=7)
    timestamp = models.DateField(auto_now_add=True, auto_now=False)
    final_date = models.DateField(auto_now_add=False, auto_now=True)
    area = models.ForeignKey(Area, on_delete=models.CASCADE)
    state = models.CharField(max_length=16, choices=CHOICES_STATE)
    status = models.BooleanField(default=True)
    slug = models.SlugField(max_length=16)

    def __str__(self):
        return self.sgg_name
    

class Goal(models.Model):
    goal_name = models.CharField(max_length=128, default="Generic Grant Goal")
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    sub_grantgoal = models.ForeignKey(SubGrantGoal, on_delete=models.CASCADE)
    description = models.CharField(max_length=256, default="Generic Grant Goal Description")
    days_durations = models.IntegerField(default=7)
    timestamp = models.DateField(auto_now_add=True, auto_now=False)
    final_date = models.DateField(auto_now_add=False, auto_now=True)
    area = models.ForeignKey(Area, on_delete=models.CASCADE)
    state = models.CharField(max_length=16, choices=CHOICES_STATE)
    status = models.BooleanField(default=True)
    slug = models.SlugField(max_length=16)

    def __str__(self):
        return self.goal_name
    

class Issue(models.Model):
    issue_name = models.CharField(max_length=128, default="Generic Grant Goal")
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    goal = models.ForeignKey(Goal, on_delete=models.CASCADE)
    description = models.CharField(max_length=256, default="Generic Grant Goal Description")
    days_durations = models.IntegerField(default=7)
    timestamp = models.DateField(auto_now_add=True, auto_now=False)
    final_date = models.DateField(auto_now_add=False, auto_now=True)
    area = models.ForeignKey(Area, on_delete=models.CASCADE)
    state = models.CharField(max_length=16, choices=CHOICES_STATE)
    status = models.BooleanField(default=True)
    slug = models.SlugField(max_length=16)

    def __str__(self):
        return self.issue_name

core/forms.py
from django import forms

from core import models


class CreateGrantGoalForm(forms.ModelForm):
    class Meta:
        model = models.GrantGoal
        exclude = [
            "timestamp",
            "final_date",
            "status"
        ]
        widgets = {
            "gg_name": forms.TextInput({"type": "text", "class": "form-control", "placeholder":"Escribe el nombre del GrantGoal"}),
            "user": forms.Select({"type": "select", "class": "form-select"}),
            "description": forms.Textarea({"type": "text", "class": "form-control", "row":3}),
            "days_durations":forms.NumberInput({"type": "number", "class": "form-control"}),
            "area": forms.Select({"type": "select", "class": "form-select"}),
            "state": forms.Select({"type": "select", "class": "form-select"}),
            "slug": forms.TextInput({"type": "text", "class": "form-control", "placeholder":"Escribe el codigo del GrantGoal"}),
        }


class UpdateGrantGoalForm(forms.ModelForm):
    class Meta:
        model = models.GrantGoal
        exclude = [
            "timestamp",
            "final_date",
        ]
        widgets = {
            "gg_name": forms.TextInput({"type": "text", "class": "form-control", "placeholder":"Escribe el nombre del GrantGoal"}),
            "user": forms.Select({"type": "select", "class": "form-select"}),
            "description": forms.Textarea({"type": "text", "class": "form-control", "row":3}),
            "days_durations":forms.NumberInput({"type": "number", "class": "form-control"}),
            "area": forms.Select({"type": "select", "class": "form-select"}),
            "state": forms.Select({"type": "select", "class": "form-select"}),
            "status": forms.CheckboxInput(attrs={"type":"checkbox", "class":"form-checkbox"}),
            "slug": forms.TextInput({"type": "text", "class": "form-control", "placeholder":"Escribe el codigo del GrantGoal"}),
        }

core/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy


from core import models
from core import forms

# Create your views here.


##### GRANT GOAL CRUD #####

## CREATE
class CreateGrantGoal(generic.CreateView):
    template_name = "core/create_gg.html"
    model = models.GrantGoal
    form_class = forms.CreateGrantGoalForm
    success_url = reverse_lazy("core:list_gg")

## RETRIEVE
# List
class ListGrantGoal(generic.View):
    template_name = "core/list_gg.html"
    context = {}

    def get(self, request):
        self.context = {
            "grantgoals": models.GrantGoal.objects.filter(status=True)
        }
        return render(request, self.template_name, self.context)

# Detail
class DetailGrantGoal(generic.View):
    template_name = "core/detail_gg.html"
    context = {}

    def get(self, request, pk):
        self.context = {
            "grant_goal": models.GrantGoal.objects.get(pk=pk)
        }
        return render(request, self.template_name, self.context)


## UPDATE
class UpdateGrantGoal(generic.UpdateView):
    template_name = "core/update_gg.html"
    model = models.GrantGoal
    form_class = forms.UpdateGrantGoalForm
    success_url = reverse_lazy("core:list_gg")


## DELETE
class DeleteGrantGoal(generic.DeleteView):    
    template_name = "core/delete_gg.html"
    model = models.GrantGoal
    success_url = reverse_lazy("core:list_gg")

templates/core/create_gg.html
{% extends "base/base.html" %}


{% block title %}CREATE NEW GRANT GOAL VIEW{% endblock title %}

{% block content %}
    <form action="" method="post" class="form">
        {% csrf_token %}
            {{ form }}
            <div class="row">
                <div class="col">
                    <button type="submit" class="btn btn-outline-success form-control">Create New Grant Goal</button>
                </div>
                <div class="col">
                    <a href="{% url 'core:list_gg' %}" class="btn btn-outline-warning form-control">Cancel</a>
                </div>
            </div>
            
            
    </form>
{% endblock content %}

templates/core/delete_gg.html
{% extends "base/base.html" %}


{% block title %}DELETE GRANT GOAL VIEW{% endblock title %}

{% block content %}
    <form action="" method="post" class="form">
        {% csrf_token %}
        <h2>¿Realmente deseas eliminar el GrantGoal: " {{ object }} " ?</h2>
            
            <div class="row">
                <div class="col">
                    <button type="submit" class="btn btn-outline-danger form-control">Delete Grant Goal</button>
                </div>
                <div class="col">
                    <a href="{% url 'core:list_gg' %}" class="btn btn-outline-warning form-control">Cancel</a>
                </div>
            </div>
            
            
    </form>
{% endblock content %}

templates/core/detail_gg.html
{% extends "base/base.html" %}

{% block title %}DETAIL GRANT GOAL VIEW{% endblock title %}

{% block content %}
    {{ grant_goal }}
    <hr>
    <a href="{% url 'core:list_gg' %}" class="btn btn-link">Return</a>
{% endblock content %}

templates/core/list_gg.html
{% extends "base/base.html" %}

{% block title %}LIST GRANT GOAL VIEW{% endblock title %}

{% block content %}
    <hr>
        <a href="{% url 'core:create_gg' %}" class="btn btn-outline-success">Create New Grant Goal</a>
    <hr>
    <table class="table table-striped">
        <thead>
            <th>Id</th>
            <th>Name</th>
            <th>User</th>
            <th>DaysDur</th>
            <th>Status</th>
            <th></th>
            <th>Actions</th>
            <th></th>
        </thead>
        <tbody>
            {% for gg in grantgoals %}
                <tr>
                    <td>{{ gg.id }}</td>
                    <td>{{ gg.gg_name }}</td>
                    <td>{{ gg.user }}</td>
                    <td>{{ gg.days_durations }}</td>
                    <td>{{ gg.status }}</td>
                    <td><a href="{% url 'core:detail_gg' gg.pk %}" class="btn btn-outline-info">Detail</a></td>
                    <td><a href="{% url 'core:update_gg' gg.pk %}" class="btn btn-outline-warning">Update</a></td>
                    <td><a href="{% url 'core:delete_gg' gg.pk %}" class="btn btn-outline-danger">Delete</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

templates/core/update_gg.html
{% extends "base/base.html" %}


{% block title %}UPDATE GRANT GOAL VIEW{% endblock title %}

{% block content %}
    <form action="" method="post" class="form">
        {% csrf_token %}
            {{ form }}
            <div class="row">
                <div class="col">
                    <button type="submit" class="btn btn-outline-success form-control">Update Grant Goal</button>
                </div>
                <div class="col">
                    <a href="{% url 'core:list_gg' %}" class="btn btn-outline-warning form-control">Cancel</a>
                </div>
            </div>
            
            
    </form>
{% endblock content %}