api/urls.py
from django.urls import path

from api import views

app_name = "api"


urlpatterns = [
    path('v1/list/grantgoal/', views.ListGrantGoalAPIView.as_view(), name="gg_list"),
    path('v1/create/grantgoal/', views.CreateGrantGoalAPIView.as_view(), name="gg_create"),
    path('v1/detail/grantgoal/<int:pk>/', views.DetailGrantGoalAPIView.as_view(), name="gg_detail"),
    path('v1/update/grantgoal/<int:pk>/', views.UpdateGrantGoalAPIView.as_view(), name="gg_update"),
    path('v1/delete/grantgoal/<int:pk>/', views.DeleteGrantGoalAPIView.as_view(), name="gg_delete"),
]

clientapi/urls.py
from django.urls import path

from clientapi import views

app_name = "clientapi"


urlpatterns = [
    path('list/grantgoal/', views.ClientListGrantGoal.as_view(), name="c_list_gg"),
    path('detail/grantgoal/<int:pk>/', views.ClientDetailGrantGoal.as_view(), name="c_detail_gg"),
]

plaestem/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('api/', include("api.urls")),
    path('core/', include("core.urls")),
    path('clientapi/', include("clientapi.urls")),
]

clientapi/models.py
from django.db import models

# Create your models here.

clientapi/views.py
from django.shortcuts import render
from django.views import generic
import requests

# Create your views here.


class ClientListGrantGoal(generic.View):
    template_name = "clientapi/c_list_gg.html"
    context = {}
    response = None
    url = "http://localhost:8000/api/v1/list/grantgoal/"

    def get(self, request):
        self.response = requests.get(self.url)
        self.context = {
            "grantgoals": self.response.json()
        }
        return render(request, self.template_name, self.context)



class ClientDetailGrantGoal(generic.View):
    template_name = "clientapi/c_detail_gg.html"
    context = {}
    url = "http://localhost:8000/api/v1/detail/grantgoal/"
    response = None

    def get(self, request, pk):
        self.url += f"{pk}/"
        self.response = requests.get(self.url)
        self.context = {
            "grant_goal": self.response.json()
        }
        return render(request, self.template_name, self.context)

templates/clientapi/c_detail_gg.html
{% extends "base/base.html" %}

{% block title %}DETAIL GRANT GOAL VIEW{% endblock title %}

{% block content %}

<div class="accordion" id="accordionExample">
    <div class="accordion-item">
      <h2 class="accordion-header">
        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
         General Data
        </button>
      </h2>
      <div id="collapseOne" class="accordion-collapse collapse show" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <strong>This is the " {{ grant_goal.gg_name }} " grant goal name.</strong> It is shown by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the <code>.accordion-body</code>, though the transition does limit overflow.
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Date Data
        </button>
      </h2>
      <div id="collapseTwo" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <strong>This is the second item's accordion body.</strong> It is hidden by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the <code>.accordion-body</code>, though the transition does limit overflow.
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          State Data
        </button>
      </h2>
      <div id="collapseThree" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <strong>This is the third item's accordion body.</strong> It is hidden by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the <code>.accordion-body</code>, though the transition does limit overflow.
        </div>
      </div>
    </div>
  </div>
    
    <hr>
    <a href="{% url 'clientapi:c_list_gg' %}" class="btn btn-link">Return</a>
{% endblock content %}

templates/clientapi/c_list_gg.html
{% extends "base/base.html" %}

{% block title %}LIST GRANT GOAL CLIENT VIEW{% endblock title %}

{% block content %}
    <table class="table">
        <thead>
            <th>ID</th>
            <th>NAME</th>
            <th>TIMESTAMP</th>
            <th>FINAL DATE</th>
            <th>STATUS</th>
            <th></th>
            <th>ACTIONS</th>
            <th></th>
        </thead>
        <tbody>
            {% for gg in grantgoals %}
                <tr>
                    <td>{{ gg.id }}</td>
                    <td>{{ gg.gg_name }}</td>
                    <td>{{ gg.timestamp }}</td>
                    <td>{{ gg.final_date }}</td>
                    <td>{{ gg.status }}</td>
                    <td><a href="{% url 'clientapi:c_detail_gg' gg.id %}" class="btn btn-info">detail</a></td>
                    <td><a href="" class="btn btn-warning">update</a></td>
                    <td><a href="" class="btn btn-danger">delete</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}